# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Configuration correcte des sessions
    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto   # Utilise HTTPS si disponible
        cookie_samesite: lax  # Empêche certaines attaques CSRF

    # Autres options importantes
    http_method_override: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
